// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldoqhlctbfzheybrvxjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxkb3FobGN0YmZ6aGV5YnJ2eGpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NzI4OTEsImV4cCI6MjA2MjQ0ODg5MX0.PI4C0U2k3X-4TPnAAk4h2-pvF_NkrpY4ZTrnTDdVa-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);